name: Release Next

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          token: ${{ secrets.PAT_JOREN }}

      - name: Set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> $GITHUB_ENV

      - name: Rename Next to Now
        run: |
          mv src/pages/next src/pages/${{env.RELEASE_DATE}}

      - name: Remake Next Dir
        run: |
          mkdir src/pages/next && cp dummy.md src/pages/next/dummy.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Joren Broekema
          author_email: joren.broekema@gmail.com
          message: 'chore: release'
          add: '.'